name: Go Benchmarks

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CI_GO_VERSION: "1.25.5"
  CI_TASK_VERSION: "3.46.3"

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        run: sh scripts/ci/checkout.sh 1

      - name: Set up Go
        run: sh scripts/ci/setup-go.sh "${{ env.CI_GO_VERSION }}"

      - name: Setup Task
        run: sh scripts/ci/setup-task.sh "${{ env.CI_TASK_VERSION }}"

      - name: Run Benchmarks
        run: task bench
