name: Go Revive Lint

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CI_GO_VERSION: "1.25.5"
  CI_TASK_VERSION: "3.46.3"
  CI_REVIVE_VERSION: "v1.15.0"

jobs:
  lint:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: sh scripts/ci/checkout.sh 1

      - name: Set up Go
        run: sh scripts/ci/setup-go.sh "${{ env.CI_GO_VERSION }}"

      - name: Setup Task
        run: sh scripts/ci/setup-task.sh "${{ env.CI_TASK_VERSION }}"

      - name: Install revive
        run: sh scripts/ci/setup-revive.sh "${{ env.CI_REVIVE_VERSION }}"

      - name: Run lint
        run: task lint
