# golang:1.27.1-alpine pinned by digest; update tag comment and digest together
FROM golang:1.27.1-alpine@sha256:4cb7ac979db5fcc41cae44b2227ba5ab8a51e8807f40d9ba4dee20a0ad960b5b

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ENV CGO_ENABLED=0
ENV GOOS=${TARGETOS}
ENV GOARCH=${TARGETARCH}
ENV GOAMD64=v1
ENV GOFLAGS=-mod=vendor
ENV GOPROXY=off


RUN apk add --no-cache git && \
    adduser -D -s /bin/sh builder

WORKDIR /build

USER builder

COPY go.mod go.sum ./
COPY vendor/ vendor/

COPY cmd/ cmd/
COPY internal/ internal/
COPY pkg/ pkg/

ARG BINARY_NAME=reticulum-go
ARG BUILD_PATH=./cmd/reticulum-go

RUN mkdir -p /dist && \
    go build \
    -ldflags='-w -s -extldflags "-static"' \
    -a -installsuffix cgo \
    -o /dist/${BINARY_NAME} \
    ${BUILD_PATH}
