#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024-2026 Quad4.io
exec 2>&1
mkdir -p /var/lib/reticulum-go/logfile
export HOME=/var/lib/reticulum-go
cd /var/lib/reticulum-go || exit 1
exec @BINDIR@/reticulum-go daemon --config /var/lib/reticulum-go/config
